// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csrflvrtcfbxaqzbiocy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzcmZsdnJ0Y2ZieGFxemJpb2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODU3NDksImV4cCI6MjA2ODM2MTc0OX0.nD83Zmf0PKLl8r_f-523eFUc8U_P9DeWhTw9ZA0FrSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});